import { randomUUID } from "node:crypto";
import { chmod, mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  DEFAULT_GENESIS_FUNDS,
  DEFAULT_SPORKS,
  DEFAULT_SPORKS_VERSION,
  DYNAMIC_PLASMA_SPORK_ID,
  LIBP2P_SPORK_ID,
  SPORK_IDS_CORRECTED_VERSION,
  TEST_SPORKS_ADDED_VERSION
} from "./constants.js";
import { multiaddrFromEnode, multiaddrFromPublicKey } from "./libp2p.js";
import { duplicateSporkIds } from "./settings.js";
import type { AppState, NetworkSettings } from "../shared/types.js";

const DATA_DIR = process.env.DATA_DIR ?? path.join(process.cwd(), "data");
const STATE_FILE = path.join(DATA_DIR, "app-state.json");
export const DEFAULT_GO_ZENON_REPO = process.env.GO_ZENON_REPO ?? "https://github.com/zenon-network/go-zenon.git";
const DEFAULT_GO_ZENON_REF = process.env.GO_ZENON_REF ?? "master";
const DEFAULT_GO_ZENON_COMMIT = process.env.GO_ZENON_COMMIT;
export const DEFAULT_DEPLOYMENT_REPO = process.env.DEPLOYMENT_REPO ?? "https://github.com/hypercore-one/deployment.git";
const DEFAULT_DEPLOYMENT_REF = process.env.DEPLOYMENT_REF ?? "main";
const DEFAULT_DEPLOYMENT_COMMIT = process.env.DEPLOYMENT_COMMIT;
let stateUpdateQueue = Promise.resolve();

/** Default genesis start for a fresh install: the first full hour at least 24 hours out, so the draft is never already in the past. */
export function defaultGenesisTimestampSec(nowMs = Date.now()): number {
  const hourMs = 3600_000;
  return (Math.ceil((nowMs + 24 * hourMs) / hourMs) * hourMs) / 1000;
}

function defaultSettings(): NetworkSettings {
  return {
    chainIdentifier: 73404,
    extraData: "Zenon Network of Momentum testnet generated by zenon-testnet-builder",
    expectedPillars: 4,
    minPillars: 3,
    genesisTimestampSec: defaultGenesisTimestampSec(),
    goZenonRepo: DEFAULT_GO_ZENON_REPO,
    goZenonRef: DEFAULT_GO_ZENON_REF,
    goZenonCommit: DEFAULT_GO_ZENON_COMMIT,
    deploymentRepo: DEFAULT_DEPLOYMENT_REPO,
    deploymentRef: DEFAULT_DEPLOYMENT_REF,
    deploymentCommit: DEFAULT_DEPLOYMENT_COMMIT,
    releaseApplyAtSec: undefined,
    wipeDataOnPublish: false,
    sporkAddress: "",
    seeders: [],
    bootstrapPeers: [],
    sporks: DEFAULT_SPORKS.map((spork) => ({ ...spork })),
    genesisFunds: DEFAULT_GENESIS_FUNDS.map((fund) => ({ ...fund }))
  };
}

function defaultState(): AppState {
  return {
    users: [],
    sessions: [],
    pillars: [],
    seedNodes: [],
    defaultSporksVersion: DEFAULT_SPORKS_VERSION,
    settings: defaultSettings()
  };
}

// Drafts saved before defaults version 3 carried the dynamic-plasma and libp2p placeholder IDs
// the wrong way round relative to go-zenon (issue #13). Nodes act on the ID, so the record labelled
// dynamic-plasma actually activated libp2p. The swap is only applied when the draft still shows the
// bug (a default-named record carrying the wrong ID) and nothing shows a hand correction (a
// default-named record carrying its right ID). It then swaps the two IDs on whichever records carry
// them, so a record keeps meaning what the admin configured it to mean even if they renamed it. A
// draft with no default-named record is ambiguous and is left for the admin to review.
function repairSwappedSporkIds(sporks: NetworkSettings["sporks"]): NetworkSettings["sporks"] {
  const isId = (spork: NetworkSettings["sporks"][number], id: string) => spork.id.toLowerCase() === id;
  const showsBug = sporks.some(
    (spork) => (spork.name === "dynamic-plasma" && isId(spork, LIBP2P_SPORK_ID)) || (spork.name === "libp2p" && isId(spork, DYNAMIC_PLASMA_SPORK_ID))
  );
  const showsCorrection = sporks.some(
    (spork) => (spork.name === "dynamic-plasma" && isId(spork, DYNAMIC_PLASMA_SPORK_ID)) || (spork.name === "libp2p" && isId(spork, LIBP2P_SPORK_ID))
  );
  if (!showsBug || showsCorrection) return sporks;
  return sporks.map((spork) => {
    if (isId(spork, LIBP2P_SPORK_ID)) return { ...spork, id: DYNAMIC_PLASMA_SPORK_ID };
    if (isId(spork, DYNAMIC_PLASMA_SPORK_ID)) return { ...spork, id: LIBP2P_SPORK_ID };
    return spork;
  });
}

function appendMissingDefaultSporks(sporks: NetworkSettings["sporks"]): NetworkSettings["sporks"] {
  const existingIds = new Set(sporks.map((spork) => spork.id.toLowerCase()));
  return [...sporks, ...DEFAULT_SPORKS.filter((spork) => !existingIds.has(spork.id.toLowerCase())).map((spork) => ({ ...spork }))];
}

/**
 * Brings the sporks of a stored draft up to DEFAULT_SPORKS_VERSION. Defaults are only appended for
 * drafts that predate them; a default an admin removed later stays removed.
 */
export function mergeDefaultSporks(sporks: NetworkSettings["sporks"], currentVersion?: number): NetworkSettings["sporks"] {
  const version = currentVersion ?? 0;
  if (version >= DEFAULT_SPORKS_VERSION) return sporks;

  let result = sporks;
  if (version < SPORK_IDS_CORRECTED_VERSION) result = repairSwappedSporkIds(result);
  if (version < TEST_SPORKS_ADDED_VERSION) result = appendMissingDefaultSporks(result);
  return result;
}

function uniqueStrings(values: Array<string | undefined>): string[] {
  return Array.from(new Set(values.filter((value): value is string => Boolean(value))));
}

function safeMultiaddrFromPublicKey(publicIp: string, p2pPort: number, publicKey: string): string | undefined {
  try {
    return multiaddrFromPublicKey(publicIp, p2pPort, publicKey);
  } catch {
    return undefined;
  }
}

export function normalizeState(state: Partial<AppState>): AppState {
  const defaults = defaultState();
  const settingsDefaults = defaultSettings();
  const settings = state.settings ?? ({} as Partial<NetworkSettings>);
  // An explicitly empty list is an admin choice and stays empty; only a missing list gets the defaults.
  const storedSporks = settings.sporks ?? settingsDefaults.sporks;
  const sporks = mergeDefaultSporks(storedSporks, state.defaultSporksVersion);
  // A finalized genesis bakes in the sporks. If the migration changed them it is stale and would
  // otherwise be preferred over the corrected settings by preview, download and publish. One that
  // contains duplicate IDs must not be published either; finalizeBlockers keeps it from coming back.
  const sporksUsable = JSON.stringify(sporks) === JSON.stringify(storedSporks) && duplicateSporkIds(sporks).length === 0;
  const finalizedGenesis = sporksUsable ? state.finalizedGenesis : undefined;
  const seeders = settings.seeders ?? settingsDefaults.seeders;
  const seedNodes = (state.seedNodes ?? []).map((seedNode) => ({
    ...seedNode,
    multiaddr:
      seedNode.multiaddr ||
      safeMultiaddrFromPublicKey(seedNode.publicIp, seedNode.p2pPort, seedNode.publicKey) ||
      ""
  }));
  const derivedBootstrapPeers = uniqueStrings([
    ...seedNodes.map((seedNode) => seedNode.multiaddr),
    ...seeders.map((seeder) => multiaddrFromEnode(seeder))
  ]);
  return {
    ...defaults,
    ...state,
    users: state.users ?? [],
    sessions: state.sessions ?? [],
    pillars: state.pillars ?? [],
    seedNodes,
    settings: {
      ...settingsDefaults,
      ...settings,
      seeders,
      bootstrapPeers: settings.bootstrapPeers ?? derivedBootstrapPeers,
      sporks,
      genesisFunds: settings.genesisFunds ?? settingsDefaults.genesisFunds
    },
    finalizedGenesis,
    defaultSporksVersion: DEFAULT_SPORKS_VERSION
  };
}

// The state file holds password hashes, session hashes, encrypted wallet passwords, and node keys.
// Keep it and its directory readable by the service user only.
const DATA_DIR_MODE = 0o700;
const STATE_FILE_MODE = 0o600;

let permissionsEnforced = false;

async function ensureDataDir(): Promise<void> {
  await mkdir(DATA_DIR, { recursive: true, mode: DATA_DIR_MODE });
  if (permissionsEnforced) return;
  // mkdir's mode only applies to directories it creates, so tighten anything that already existed
  // (deployments created before these modes were enforced). This fails closed: if the modes cannot
  // be enforced the error propagates and the caller (ultimately startup) fails, and the flag stays
  // unset so the next call tries again.
  await chmod(DATA_DIR, DATA_DIR_MODE);
  await chmod(STATE_FILE, STATE_FILE_MODE).catch((error: NodeJS.ErrnoException) => {
    if (error.code !== "ENOENT") throw error;
  });
  permissionsEnforced = true;
}

function findJsonValueEnd(content: string, start: number): number | undefined {
  let depth = 0;
  let inString = false;
  let escaped = false;
  let started = false;

  for (let index = start; index < content.length; index += 1) {
    const char = content[index];
    if (!started) {
      if (/\s/.test(char)) continue;
      if (char !== "{" && char !== "[") return undefined;
      started = true;
    }

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
    } else if (char === "{" || char === "[") {
      depth += 1;
    } else if (char === "}" || char === "]") {
      depth -= 1;
      if (depth === 0) return index + 1;
      if (depth < 0) return undefined;
    }
  }

  return undefined;
}

function parseCompleteJsonValues(content: string): Array<{ value: unknown; end: number }> {
  const values: Array<{ value: unknown; end: number }> = [];
  let offset = 0;

  while (offset < content.length) {
    while (offset < content.length && /\s/.test(content[offset])) offset += 1;
    if (offset >= content.length) break;

    const end = findJsonValueEnd(content, offset);
    if (!end) break;

    try {
      values.push({ value: JSON.parse(content.slice(offset, end)), end });
      offset = end;
    } catch {
      break;
    }
  }

  return values;
}

function parseStateContent(content: string): { state: AppState; recovered: boolean; recoveredValueCount: number; trailingCharacters: number } {
  try {
    return {
      state: JSON.parse(content) as AppState,
      recovered: false,
      recoveredValueCount: 1,
      trailingCharacters: 0
    };
  } catch (error) {
    const values = parseCompleteJsonValues(content);
    const latest = values.at(-1);
    if (!latest) throw error;
    return {
      state: latest.value as AppState,
      recovered: true,
      recoveredValueCount: values.length,
      trailingCharacters: content.length - latest.end
    };
  }
}

async function writeAtomic(filePath: string, content: string): Promise<void> {
  await ensureDataDir();
  const tempFile = path.join(DATA_DIR, `.${path.basename(filePath)}.${process.pid}.${Date.now()}.${randomUUID()}.tmp`);
  await writeFile(tempFile, content, { encoding: "utf8", mode: STATE_FILE_MODE });
  try {
    await rename(tempFile, filePath);
  } catch (error) {
    await unlink(tempFile).catch(() => undefined);
    throw error;
  }
}

async function backupCorruptState(content: string): Promise<string> {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupFile = path.join(DATA_DIR, `app-state.corrupt-${stamp}-${process.pid}.json`);
  await writeAtomic(backupFile, content);
  return backupFile;
}

export async function readState(): Promise<AppState> {
  await ensureDataDir();
  try {
    const content = await readFile(STATE_FILE, "utf8");
    const parsed = parseStateContent(content);
    const state = normalizeState(parsed.state);
    if (parsed.recovered) {
      const backupFile = await backupCorruptState(content);
      await writeState(state);
      console.warn(
        `Recovered ${STATE_FILE} from ${parsed.recoveredValueCount} complete JSON value(s); ` +
          `${parsed.trailingCharacters} trailing character(s) were ignored. Original saved to ${backupFile}.`
      );
    }
    return state;
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      const state = defaultState();
      await writeState(state);
      return state;
    }
    throw error;
  }
}

export async function writeState(state: AppState): Promise<void> {
  await writeAtomic(STATE_FILE, `${JSON.stringify(state, null, 2)}\n`);
}

export async function updateState<T>(mutator: (state: AppState) => Promise<T> | T): Promise<T> {
  const run = async () => {
    const state = await readState();
    const result = await mutator(state);
    await writeState(state);
    return result;
  };
  const next = stateUpdateQueue.then(run, run);
  stateUpdateQueue = next.then(
    () => undefined,
    () => undefined
  );
  return next;
}
