import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { DEFAULT_SPORKS } from "./constants.js";
import type { AppState, NetworkSettings } from "../shared/types.js";

const DATA_DIR = process.env.DATA_DIR ?? path.join(process.cwd(), "data");
const STATE_FILE = path.join(DATA_DIR, "app-state.json");
const DEFAULT_GO_ZENON_REPO = process.env.GO_ZENON_REPO ?? "https://github.com/zenon-network/go-zenon.git";
const DEFAULT_GO_ZENON_REF = process.env.GO_ZENON_REF ?? "master";
const DEFAULT_GO_ZENON_COMMIT = process.env.GO_ZENON_COMMIT;
const DEFAULT_DEPLOYMENT_REPO = process.env.DEPLOYMENT_REPO ?? "https://github.com/hypercore-one/deployment.git";
const DEFAULT_DEPLOYMENT_REF = process.env.DEPLOYMENT_REF ?? "main";

function defaultSettings(): NetworkSettings {
  return {
    chainIdentifier: 73404,
    extraData: "Zenon Network of Momentum testnet generated by zenon-testnet-builder",
    expectedPillars: 4,
    minPillars: 3,
    genesisTimestampSec: Math.floor(Date.now() / 1000),
    goZenonRepo: DEFAULT_GO_ZENON_REPO,
    goZenonRef: DEFAULT_GO_ZENON_REF,
    goZenonCommit: DEFAULT_GO_ZENON_COMMIT,
    deploymentRepo: DEFAULT_DEPLOYMENT_REPO,
    deploymentRef: DEFAULT_DEPLOYMENT_REF,
    sporkAddress: "",
    seeders: [],
    sporks: DEFAULT_SPORKS.map((spork) => ({ ...spork }))
  };
}

function defaultState(): AppState {
  return {
    users: [],
    sessions: [],
    pillars: [],
    settings: defaultSettings()
  };
}

async function ensureDataDir(): Promise<void> {
  await mkdir(DATA_DIR, { recursive: true });
}

export async function readState(): Promise<AppState> {
  await ensureDataDir();
  try {
    const content = await readFile(STATE_FILE, "utf8");
    const state = JSON.parse(content) as AppState;
    return {
      ...defaultState(),
      ...state,
      settings: {
        ...defaultSettings(),
        ...state.settings,
        sporks: state.settings?.sporks?.length ? state.settings.sporks : defaultSettings().sporks
      }
    };
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      const state = defaultState();
      await writeState(state);
      return state;
    }
    throw error;
  }
}

export async function writeState(state: AppState): Promise<void> {
  await ensureDataDir();
  const tempFile = `${STATE_FILE}.${process.pid}.tmp`;
  await writeFile(tempFile, `${JSON.stringify(state, null, 2)}\n`, "utf8");
  await rename(tempFile, STATE_FILE);
}

export async function updateState<T>(mutator: (state: AppState) => Promise<T> | T): Promise<T> {
  const state = await readState();
  const result = await mutator(state);
  await writeState(state);
  return result;
}
