import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { DEFAULT_SPORKS, DEFAULT_SPORKS_VERSION } from "./constants.js";
import type { AppState, NetworkSettings } from "../shared/types.js";

const DATA_DIR = process.env.DATA_DIR ?? path.join(process.cwd(), "data");
const STATE_FILE = path.join(DATA_DIR, "app-state.json");
const DEFAULT_GO_ZENON_REPO = process.env.GO_ZENON_REPO ?? "https://github.com/zenon-network/go-zenon.git";
const DEFAULT_GO_ZENON_REF = process.env.GO_ZENON_REF ?? "master";
const DEFAULT_GO_ZENON_COMMIT = process.env.GO_ZENON_COMMIT;
const DEFAULT_DEPLOYMENT_REPO = process.env.DEPLOYMENT_REPO ?? "https://github.com/hypercore-one/deployment.git";
const DEFAULT_DEPLOYMENT_REF = process.env.DEPLOYMENT_REF ?? "main";
let stateUpdateQueue = Promise.resolve();

function defaultSettings(): NetworkSettings {
  return {
    chainIdentifier: 73404,
    extraData: "Zenon Network of Momentum testnet generated by zenon-testnet-builder",
    expectedPillars: 4,
    minPillars: 3,
    genesisTimestampSec: Math.floor(Date.now() / 1000),
    goZenonRepo: DEFAULT_GO_ZENON_REPO,
    goZenonRef: DEFAULT_GO_ZENON_REF,
    goZenonCommit: DEFAULT_GO_ZENON_COMMIT,
    deploymentRepo: DEFAULT_DEPLOYMENT_REPO,
    deploymentRef: DEFAULT_DEPLOYMENT_REF,
    releaseApplyAtSec: undefined,
    wipeDataOnPublish: false,
    sporkAddress: "",
    seeders: [],
    sporks: DEFAULT_SPORKS.map((spork) => ({ ...spork }))
  };
}

function defaultState(): AppState {
  return {
    users: [],
    sessions: [],
    pillars: [],
    seedNodes: [],
    defaultSporksVersion: DEFAULT_SPORKS_VERSION,
    settings: defaultSettings()
  };
}

function mergeDefaultSporks(sporks: NetworkSettings["sporks"], currentVersion?: number): NetworkSettings["sporks"] {
  if (currentVersion && currentVersion >= DEFAULT_SPORKS_VERSION) return sporks;

  const existingIds = new Set(sporks.map((spork) => spork.id.toLowerCase()));
  return [
    ...sporks,
    ...DEFAULT_SPORKS.filter((spork) => !existingIds.has(spork.id.toLowerCase())).map((spork) => ({ ...spork }))
  ];
}

function normalizeState(state: Partial<AppState>): AppState {
  const defaults = defaultState();
  const settingsDefaults = defaultSettings();
  const settings = state.settings ?? ({} as Partial<NetworkSettings>);
  const sporks = settings.sporks?.length ? settings.sporks : settingsDefaults.sporks;
  return {
    ...defaults,
    ...state,
    users: state.users ?? [],
    sessions: state.sessions ?? [],
    pillars: state.pillars ?? [],
    seedNodes: state.seedNodes ?? [],
    settings: {
      ...settingsDefaults,
      ...settings,
      sporks: mergeDefaultSporks(sporks, state.defaultSporksVersion)
    },
    defaultSporksVersion: DEFAULT_SPORKS_VERSION
  };
}

async function ensureDataDir(): Promise<void> {
  await mkdir(DATA_DIR, { recursive: true });
}

function findJsonValueEnd(content: string, start: number): number | undefined {
  let depth = 0;
  let inString = false;
  let escaped = false;
  let started = false;

  for (let index = start; index < content.length; index += 1) {
    const char = content[index];
    if (!started) {
      if (/\s/.test(char)) continue;
      if (char !== "{" && char !== "[") return undefined;
      started = true;
    }

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
    } else if (char === "{" || char === "[") {
      depth += 1;
    } else if (char === "}" || char === "]") {
      depth -= 1;
      if (depth === 0) return index + 1;
      if (depth < 0) return undefined;
    }
  }

  return undefined;
}

function parseCompleteJsonValues(content: string): Array<{ value: unknown; end: number }> {
  const values: Array<{ value: unknown; end: number }> = [];
  let offset = 0;

  while (offset < content.length) {
    while (offset < content.length && /\s/.test(content[offset])) offset += 1;
    if (offset >= content.length) break;

    const end = findJsonValueEnd(content, offset);
    if (!end) break;

    try {
      values.push({ value: JSON.parse(content.slice(offset, end)), end });
      offset = end;
    } catch {
      break;
    }
  }

  return values;
}

function parseStateContent(content: string): { state: AppState; recovered: boolean; recoveredValueCount: number; trailingCharacters: number } {
  try {
    return {
      state: JSON.parse(content) as AppState,
      recovered: false,
      recoveredValueCount: 1,
      trailingCharacters: 0
    };
  } catch (error) {
    const values = parseCompleteJsonValues(content);
    const latest = values.at(-1);
    if (!latest) throw error;
    return {
      state: latest.value as AppState,
      recovered: true,
      recoveredValueCount: values.length,
      trailingCharacters: content.length - latest.end
    };
  }
}

async function writeAtomic(filePath: string, content: string): Promise<void> {
  await ensureDataDir();
  const tempFile = path.join(DATA_DIR, `.${path.basename(filePath)}.${process.pid}.${Date.now()}.${randomUUID()}.tmp`);
  await writeFile(tempFile, content, "utf8");
  try {
    await rename(tempFile, filePath);
  } catch (error) {
    await unlink(tempFile).catch(() => undefined);
    throw error;
  }
}

async function backupCorruptState(content: string): Promise<string> {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupFile = path.join(DATA_DIR, `app-state.corrupt-${stamp}-${process.pid}.json`);
  await writeAtomic(backupFile, content);
  return backupFile;
}

export async function readState(): Promise<AppState> {
  await ensureDataDir();
  try {
    const content = await readFile(STATE_FILE, "utf8");
    const parsed = parseStateContent(content);
    const state = normalizeState(parsed.state);
    if (parsed.recovered) {
      const backupFile = await backupCorruptState(content);
      await writeState(state);
      console.warn(
        `Recovered ${STATE_FILE} from ${parsed.recoveredValueCount} complete JSON value(s); ` +
          `${parsed.trailingCharacters} trailing character(s) were ignored. Original saved to ${backupFile}.`
      );
    }
    return state;
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      const state = defaultState();
      await writeState(state);
      return state;
    }
    throw error;
  }
}

export async function writeState(state: AppState): Promise<void> {
  await writeAtomic(STATE_FILE, `${JSON.stringify(state, null, 2)}\n`);
}

export async function updateState<T>(mutator: (state: AppState) => Promise<T> | T): Promise<T> {
  const run = async () => {
    const state = await readState();
    const result = await mutator(state);
    await writeState(state);
    return result;
  };
  const next = stateUpdateQueue.then(run, run);
  stateUpdateQueue = next.then(
    () => undefined,
    () => undefined
  );
  return next;
}
